
@startuml




    actor User AS user

package "BriarJar (GUI/TUI)" {
left to right direction

        usecase ac AS "Add Contact"
        usecase cwc AS "Chat with Contact"
        usecase acdn AS "Alter Contact's Alias"
        usecase dlchpc AS "Delete\nlocal Chat History\nper Contact"
        usecase rc AS "Remove Contact"
        usecase da AS "Delete Account"

        usecase gocl AS "Get own Contact Link"
        usecase an AS "Assign Alias"

        user -- ac
        user -- cwc
        user -- acdn
        user -- dlchpc
        user -- rc
        user -- da

        ac .. gocl : <<include>>
        ac .. an : <<include>>

        note "Version: 1.0 (2022-02-19)" as version
}

@enduml
