/*
 * BriarJar -- a GUI and TUI prototype for the messenger Briar.
 * Copyright (C) 2022 BriarJar Project Team
 *
 * This file is part of BriarJar.
 *
 * BriarJar is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * BriarJar is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with BriarJar.  If not, see <https://www.gnu.org/licenses/>.
 */

@startuml




    actor User AS user

package "BriarJar (GUI/TUI)" {
left to right direction

        usecase ac AS "Add Contact"
        usecase cwc AS "Chat with Contact"
        usecase acdn AS "Alter Contact's Alias"
        usecase dlchpc AS "Delete\nlocal Chat History\nper Contact"
        usecase rc AS "Remove Contact"
        usecase da AS "Delete Account"

        usecase gocl AS "Get own Contact Link"
        usecase an AS "Assign Alias"

        user -- ac
        user -- cwc
        user -- acdn
        user -- dlchpc
        user -- rc
        user -- da

        ac .. gocl : <<include>>
        ac .. an : <<include>>

        note "Version: 1.0 (2022-02-19)" as version
}

@enduml
