
@startuml

note "=Version: DRAFT (2022-01-31)\n\n===Further needs/possibilities:\n\
*?\n" as version
( ) .down. version



    actor User AS user

package "BriarJar (GUI/TUI)" {
left to right direction

        usecase ac AS "Add Contact"
        usecase cwc AS "Chat with Contact"
        usecase acdn AS "Alter Contact's\nDisplay Name"
        usecase dlchpc AS "Delete\nlocal Chat History\nper Contact"
        usecase rc AS "Remove Contact"
        usecase da AS "Delete Account"

        usecase gocl AS "Get own Contact Link"
        usecase an AS "Assign\nDisplay Name"

        user -- ac
        user -- cwc
        user -- acdn
        user -- dlchpc
        user -- rc
        user -- da

        ac .. gocl : <<include>>
        ac .. an : <<include>>
}

@enduml
