@startuml

class ViewModelProvider {
    loginVM: LoginViewModel
    contactVM: ContactViewModel
    conversationVM: ConversationViewModel
}

class LoginViewModel implements ViewModel {
    username: String
    passphrase: String
    login()
    register()
    passwordStrength()
}

class ContactViewModel implements ViewModel {

}
class ConversationViewModel implements ViewModel {

}


interface ViewModel {
    empty interface
}

class Main {
    ui: UserInterface
}

class BriarJarUiImpl {
    viewModelProvider: ViewModelProvider
    mainTUI: MainTUI
    mainGUI: MainGUI
}

class MainTUI {
    viewModelProvider: ViewModelProvider
}

class MainGUI {
    viewModelProvider: ViewModelProvider
}

class RootBorderPane {

}

enum UserInterface {
    GRAPHICAL,
    TERMINAL
}

Main  -down-> BriarJarUiImpl
BriarJarUiImpl -right-> ViewModelProvider
MainGUI -up-> BriarJarUiImpl
RootBorderPane -up-> MainGUI
MainTUI -> BriarJarUiImpl

ViewModelProvider -up-> LoginViewModel
ViewModelProvider -up-> ContactViewModel
ViewModelProvider -up-> ConversationViewModel
@enduml